// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Persistence.Context
{
    public partial class WerewolfContext : DbContext, IWerewolfContext
    {
        public WerewolfContext()
        {
        }

        public WerewolfContext(DbContextOptions<WerewolfContext> options)
            : base(options)
        {
        }

        public override async Task<int> SaveChangesAsync(CancellationToken cancellationToken = new CancellationToken()) => await base.SaveChangesAsync(cancellationToken);

        public virtual DbSet<AmRole> AmRoles { get; set; }
        public virtual DbSet<AmTemplate> AmTemplates { get; set; }
        public virtual DbSet<AutoDusk> AutoDusks { get; set; }
        public virtual DbSet<Bio> Bios { get; set; }
        public virtual DbSet<CcInfo> CcInfos { get; set; }
        public virtual DbSet<CcPlayer> CcPlayers { get; set; }
        public virtual DbSet<ChatMessage> ChatMessages { get; set; }
        public virtual DbSet<ChatMessageAction> ChatMessageActions { get; set; }
        public virtual DbSet<ChatRoom> ChatRooms { get; set; }
        public virtual DbSet<ChatUser> ChatUsers { get; set; }
        public virtual DbSet<Exit> Exits { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameDayLog> GameDayLogs { get; set; }
        public virtual DbSet<GameOrder> GameOrders { get; set; }
        public virtual DbSet<GameSeries> GameSeries { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemOrder> ItemOrders { get; set; }
        public virtual DbSet<ItemTemplate> ItemTemplates { get; set; }
        public virtual DbSet<LocExit> LocExits { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<MiscUser> MiscUsers { get; set; }
        public virtual DbSet<Moderator> Moderators { get; set; }
        public virtual DbSet<MoveOrder> MoveOrders { get; set; }
        public virtual DbSet<PhysicsProcessing> PhysicsProcessings { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<PostCollectSlot> PostCollectSlots { get; set; }
        public virtual DbSet<Replacement> Replacements { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SocialSite> SocialSites { get; set; }
        public virtual DbSet<SocialUser> SocialUsers { get; set; }
        public virtual DbSet<Stat> Stats { get; set; }
        public virtual DbSet<Tally> Tallies { get; set; }
        public virtual DbSet<Timezone> Timezones { get; set; }
        public virtual DbSet<UpdateCalendar> UpdateCalendars { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersNgram> UsersNgrams { get; set; }
        public virtual DbSet<Vote> Votes { get; set; }
        public virtual DbSet<WolfyAward> WolfyAwards { get; set; }
        public virtual DbSet<WolfyGame> WolfyGames { get; set; }
        public virtual DbSet<WolfyPlayer> WolfyPlayers { get; set; }
        public virtual DbSet<Wotw> Wotws { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasCharSet("latin1")
                .UseCollation("latin1_swedish_ci");

            modelBuilder.ApplyConfiguration(new Configurations.AmRoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AmTemplateConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.AutoDuskConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.BioConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CcInfoConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.CcPlayerConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ChatMessageConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ChatMessageActionConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ChatRoomConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ChatUserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ExitConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.GameConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.GameDayLogConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.GameOrderConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.GameSeriesConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ItemConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ItemOrderConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ItemTemplateConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LocExitConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.LocationConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MiscUserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ModeratorConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.MoveOrderConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PhysicsProcessingConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PlayerConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PostConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.PostCollectSlotConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.ReplacementConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoleConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SocialSiteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.SocialUserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.StatConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TallyConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.TimezoneConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UpdateCalendarConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UsersNgramConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.VoteConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WolfyAwardConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WolfyGameConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WolfyPlayerConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.WotwConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
