// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class AmTemplateConfiguration : IEntityTypeConfiguration<AmTemplate>
    {
        public void Configure(EntityTypeBuilder<AmTemplate> entity)
        {
            entity.ToTable("AM_template");

            entity.Property(e => e.Id)
                .HasColumnType("int(2) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("description");

            entity.Property(e => e.Mode)
                .IsRequired()
                .HasColumnType("enum('Edit','Test','Active')")
                .HasColumnName("mode")
                .HasDefaultValueSql("'Edit'");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(80)
                .HasColumnName("name");

            entity.Property(e => e.NumPlayerSets)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("num_player_sets")
                .HasDefaultValueSql("'0'");

            entity.Property(e => e.NumPlayers)
                .HasColumnType("int(2)")
                .HasColumnName("num_players");

            entity.Property(e => e.OwnerId)
                .HasColumnType("smallint(4) unsigned zerofill")
                .HasColumnName("owner_id");

            entity.Property(e => e.PriestType)
                .IsRequired()
                .HasColumnType("enum('none','choose','lynch','all','passive')")
                .HasColumnName("priest_type")
                .HasDefaultValueSql("'none'")
                .HasComment("if changed edit expand_priest_type in edit_functions.php");

            entity.Property(e => e.RandomN0)
                .IsRequired()
                .HasColumnType("enum('yes','no')")
                .HasColumnName("random_n0")
                .HasDefaultValueSql("'yes'");

            entity.Property(e => e.RandomTinker)
                .HasColumnName("random_tinker")
                .HasComment("0=false, 1=true");

            entity.Property(e => e.RandomWhitehat)
                .HasColumnName("random_whitehat")
                .HasComment("0=false, 1=true");

            entity.Property(e => e.RoleReveal)
                .IsRequired()
                .HasColumnType("enum('yes','no')")
                .HasColumnName("role_reveal")
                .HasDefaultValueSql("'yes'")
                .HasComment("If changed edit \"expand_role_reveal\" in edit_functions.php");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AmTemplate> entity);
    }
}
