// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class AutoDuskConfiguration : IEntityTypeConfiguration<AutoDusk>
    {
        public void Configure(EntityTypeBuilder<AutoDusk> entity)
        {
            entity.HasKey(e => e.GameId)
                .HasName("PRIMARY");

            entity.ToTable("Auto_dusk");

            entity.Property(e => e.GameId)
                .HasColumnType("smallint(4) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("game_id");

            entity.Property(e => e.Fri).HasColumnName("fri");

            entity.Property(e => e.Mon).HasColumnName("mon");

            entity.Property(e => e.Sat).HasColumnName("sat");

            entity.Property(e => e.Sun).HasColumnName("sun");

            entity.Property(e => e.Thu).HasColumnName("thu");

            entity.Property(e => e.Tue).HasColumnName("tue");

            entity.Property(e => e.Wed).HasColumnName("wed");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AutoDusk> entity);
    }
}
