// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class BioConfiguration : IEntityTypeConfiguration<Bio>
    {
        public void Configure(EntityTypeBuilder<Bio> entity)
        {
            entity.HasKey(e => e.UserId)
                .HasName("PRIMARY");

            entity.ToTable("Bio");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("user_id");

            entity.Property(e => e.Avatar)
                .HasMaxLength(60)
                .HasColumnName("avatar")
                .HasComment("BGG Avatar");

            entity.Property(e => e.BDate)
                .HasColumnType("date")
                .HasColumnName("b_date")
                .HasComment("Birthday");

            entity.Property(e => e.ChatColor)
                .HasMaxLength(7)
                .HasColumnName("chat_color")
                .HasDefaultValueSql("'#000000'")
                .HasComment("Chat Color Preference");

            entity.Property(e => e.Comments)
                .HasColumnType("text")
                .HasColumnName("comments")
                .HasComment("Anything Else");

            entity.Property(e => e.EmailAddr)
                .HasMaxLength(50)
                .HasColumnName("email_addr")
                .HasComment("E-mail Address");

            entity.Property(e => e.Family)
                .HasColumnType("text")
                .HasColumnName("family")
                .HasComment("Family");

            entity.Property(e => e.FreeHours)
                .HasColumnType("text")
                .HasColumnName("free_hours")
                .HasComment("Typical Hours to Play WW");

            entity.Property(e => e.Gender)
                .HasColumnType("enum('M','F')")
                .HasColumnName("gender")
                .HasComment("Gender");

            entity.Property(e => e.Job)
                .HasColumnType("text")
                .HasColumnName("job")
                .HasComment("Job");

            entity.Property(e => e.Location)
                .HasMaxLength(100)
                .HasColumnName("location")
                .HasComment("Location");

            entity.Property(e => e.MaxMessages)
                .HasColumnType("int(11)")
                .HasColumnName("max_messages")
                .HasDefaultValueSql("'50'")
                .HasComment("Max New Chat Posts (0=All)");

            entity.Property(e => e.Mbti)
                .HasColumnType("text")
                .HasColumnName("mbti")
                .HasComment("<a href='http://en.wikipedia.org/wiki/MBTI'>MBTI</a>");

            entity.Property(e => e.NameOrigin)
                .HasColumnType("text")
                .HasColumnName("name_origin")
                .HasComment("Origin of Username");

            entity.Property(e => e.Religion)
                .HasColumnType("text")
                .HasColumnName("religion")
                .HasComment("Religion");

            entity.Property(e => e.RlName)
                .HasMaxLength(50)
                .HasColumnName("rl_name")
                .HasComment("Real Life Name");

            entity.Property(e => e.TimeZone)
                .HasMaxLength(1)
                .HasColumnName("time_zone")
                .HasComment("Time Zone");

            entity.Property(e => e.TwitterName)
                .HasMaxLength(50)
                .HasColumnName("twitter_name")
                .HasComment("Twitter Name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Bio> entity);
    }
}
