// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class ChatMessageConfiguration : IEntityTypeConfiguration<ChatMessage>
    {
        public void Configure(EntityTypeBuilder<ChatMessage> entity)
        {
            entity.ToTable("Chat_messages");

            entity.HasIndex(e => new { e.RoomId, e.PostTime }, "Chat_messages_room_id_idx");

            entity.HasIndex(e => e.UserId, "Chat_messages_user_id_idx");

            entity.Property(e => e.Id)
                .HasColumnType("int(11) unsigned")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Message)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("message");

            entity.Property(e => e.PostTime)
                .HasColumnType("datetime")
                .HasColumnName("post_time");

            entity.Property(e => e.RoomId)
                .HasColumnType("int(5)")
                .HasColumnName("room_id");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3)")
                .HasColumnName("user_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChatMessage> entity);
    }
}
