// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class ChatUserConfiguration : IEntityTypeConfiguration<ChatUser>
    {
        public void Configure(EntityTypeBuilder<ChatUser> entity)
        {
            entity.HasKey(e => new { e.UserId, e.RoomId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("Chat_users");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .HasColumnName("user_id");

            entity.Property(e => e.RoomId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("room_id");

            entity.Property(e => e.Alias)
                .HasMaxLength(50)
                .HasColumnName("alias");

            entity.Property(e => e.Close)
                .HasColumnType("datetime")
                .HasColumnName("close");

            entity.Property(e => e.Color)
                .IsRequired()
                .HasMaxLength(7)
                .HasColumnName("color")
                .HasDefaultValueSql("'#000000'");

            entity.Property(e => e.LastView)
                .HasColumnType("datetime")
                .HasColumnName("last_view");

            entity.Property(e => e.Lock)
                .IsRequired()
                .HasColumnType("enum('Off','On','Secure')")
                .HasColumnName("lock")
                .HasDefaultValueSql("'Off'");

            entity.Property(e => e.MaxPost)
                .HasColumnType("int(11)")
                .HasColumnName("max_post");

            entity.Property(e => e.Open)
                .HasColumnType("datetime")
                .HasColumnName("open");

            entity.Property(e => e.RemainingPost)
                .HasColumnType("int(11)")
                .HasColumnName("remaining_post");

            entity.Property(e => e.Secret)
                .HasColumnType("enum('on','')")
                .HasColumnName("secret");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChatUser> entity);
    }
}
