// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class ChatRoomConfiguration : IEntityTypeConfiguration<ChatRoom>
    {
        public void Configure(EntityTypeBuilder<ChatRoom> entity)
        {
            entity.ToTable("Chat_rooms");

            entity.HasIndex(e => e.GameId, "Chat_room_game_id_idx");

            entity.Property(e => e.Id)
                .HasColumnType("int(5) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Created)
                .HasColumnType("datetime")
                .HasColumnName("created");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4) unsigned zerofill")
                .HasColumnName("game_id");

            entity.Property(e => e.Lock)
                .IsRequired()
                .HasColumnType("enum('Off','On','Secure')")
                .HasColumnName("lock")
                .HasDefaultValueSql("'Off'");

            entity.Property(e => e.MaxPost)
                .HasColumnType("int(11)")
                .HasColumnName("max_post");

            entity.Property(e => e.Monitor)
                .HasColumnType("int(1)")
                .HasColumnName("monitor");

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(60)
                .HasColumnName("name");

            entity.Property(e => e.RemainingPost)
                .HasColumnType("int(11)")
                .HasColumnName("remaining_post");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ChatRoom> entity);
    }
}
