// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class GameOrderConfiguration : IEntityTypeConfiguration<GameOrder>
    {
        public void Configure(EntityTypeBuilder<GameOrder> entity)
        {
            entity.ToTable("Game_orders");

            entity.HasIndex(e => new { e.GameId, e.UserId }, "game_id");

            entity.Property(e => e.Id)
                .HasColumnType("int(5) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Cancel)
                .HasColumnType("smallint(1)")
                .HasColumnName("cancel");

            entity.Property(e => e.Day)
                .HasColumnType("int(2)")
                .HasColumnName("day");

            entity.Property(e => e.Desc)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("desc");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4)")
                .HasColumnName("game_id");

            entity.Property(e => e.LastUpdated)
                .HasColumnType("timestamp")
                .HasColumnName("last_updated")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.Property(e => e.TargetId)
                .HasColumnType("int(3)")
                .HasColumnName("target_id");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3)")
                .HasColumnName("user_id");

            entity.Property(e => e.UserText)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("user_text");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<GameOrder> entity);
    }
}
