// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class ItemOrderConfiguration : IEntityTypeConfiguration<ItemOrder>
    {
        public void Configure(EntityTypeBuilder<ItemOrder> entity)
        {
            entity.ToTable("Item_orders");

            entity.HasIndex(e => e.GameId, "game_id");

            entity.Property(e => e.Id)
                .HasColumnType("int(5) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.GameId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("game_id");

            entity.Property(e => e.ItemId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("item_id");

            entity.Property(e => e.LastUpdated)
                .HasColumnType("timestamp")
                .HasColumnName("last_updated")
                .HasDefaultValueSql("CURRENT_TIMESTAMP");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasColumnType("enum('active','canceled','processed')")
                .HasColumnName("status")
                .HasDefaultValueSql("'active'");

            entity.Property(e => e.TargetId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("target_id");

            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasColumnType("enum('user','loc')")
                .HasColumnName("target_type");

            entity.Property(e => e.UserId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("user_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ItemOrder> entity);
    }
}
