// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class LocExitConfiguration : IEntityTypeConfiguration<LocExit>
    {
        public void Configure(EntityTypeBuilder<LocExit> entity)
        {
            entity.HasKey(e => new { e.LocFromId, e.ExitId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("Loc_exits");

            entity.HasIndex(e => e.ExitId, "exit_id");

            entity.Property(e => e.LocFromId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("loc_from_id");

            entity.Property(e => e.ExitId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("exit_id");

            entity.Property(e => e.LocToId)
                .HasColumnType("int(5) unsigned zerofill")
                .HasColumnName("loc_to_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<LocExit> entity);
    }
}
