// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class MiscUserConfiguration : IEntityTypeConfiguration<MiscUser>
    {
        public void Configure(EntityTypeBuilder<MiscUser> entity)
        {
            entity.HasKey(e => e.UserId)
                .HasName("PRIMARY");

            entity.ToTable("Misc_users");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("user_id");

            entity.Property(e => e.GoogleCalendar)
                .HasColumnType("text")
                .HasColumnName("google_calendar");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<MiscUser> entity);
    }
}
