// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class PhysicsProcessingConfiguration : IEntityTypeConfiguration<PhysicsProcessing>
    {
        public void Configure(EntityTypeBuilder<PhysicsProcessing> entity)
        {
            entity.ToTable("Physics_processing");

            entity.Property(e => e.Id)
                .HasColumnType("int(5) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Frequency)
                .IsRequired()
                .HasColumnType("enum('7daily','5daily','hourly','2hourly','30mins','15mins','immediate')")
                .HasColumnName("frequency");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4) unsigned zerofill")
                .HasColumnName("game_id");

            entity.Property(e => e.Hour)
                .HasColumnType("tinyint(2) unsigned")
                .HasColumnName("hour");

            entity.Property(e => e.LastRun)
                .HasColumnType("datetime")
                .HasColumnName("last_run");

            entity.Property(e => e.Minute)
                .HasColumnType("tinyint(2) unsigned")
                .HasColumnName("minute");

            entity.Property(e => e.Type)
                .IsRequired()
                .HasColumnType("enum('item','movement')")
                .HasColumnName("type");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PhysicsProcessing> entity);
    }
}
