// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class PostCollectSlotConfiguration : IEntityTypeConfiguration<PostCollectSlot>
    {
        public void Configure(EntityTypeBuilder<PostCollectSlot> entity)
        {
            entity.ToTable("Post_collect_slots");

            entity.Property(e => e.Id)
                .HasColumnType("bigint(20)")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.GameId)
                .HasColumnType("int(10) unsigned")
                .HasColumnName("game_id");

            entity.Property(e => e.LastDumped)
                .HasColumnType("datetime")
                .HasColumnName("last_dumped");

            entity.Property(e => e.Minute)
                .HasColumnType("tinyint(3) unsigned")
                .HasColumnName("minute");

            entity.Property(e => e.RunOrder)
                .HasColumnType("tinyint(4)")
                .HasColumnName("run_order");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<PostCollectSlot> entity);
    }
}
