// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class PostConfiguration : IEntityTypeConfiguration<Post>
    {
        public void Configure(EntityTypeBuilder<Post> entity)
        {
            entity.HasKey(e => e.ArticleId)
                .HasName("PRIMARY");

            entity.HasIndex(e => new { e.GameId, e.UserId }, "group_user_idx");

            entity.HasIndex(e => e.Page, "page_idx");

            entity.HasIndex(e => e.Text, "text")
                .HasAnnotation("MySql:FullTextIndex", true);

            entity.Property(e => e.ArticleId)
                .HasColumnType("int(10)")
                .ValueGeneratedNever()
                .HasColumnName("article_id");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4) unsigned zerofill")
                .HasColumnName("game_id")
                .HasDefaultValueSql("'0000'");

            entity.Property(e => e.NumEdits)
                .HasColumnType("int(3)")
                .HasColumnName("num_edits");

            entity.Property(e => e.Page)
                .HasColumnType("int(3)")
                .HasColumnName("page");

            entity.Property(e => e.Text)
                .IsRequired()
                .HasColumnType("text")
                .HasColumnName("text");

            entity.Property(e => e.TimeStamp)
                .HasColumnType("datetime")
                .HasColumnName("time_stamp")
                .HasDefaultValueSql("'0000-00-00 00:00:00'");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .HasColumnName("user_id")
                .HasDefaultValueSql("'000'");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Post> entity);
    }
}
