// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class ReplacementConfiguration : IEntityTypeConfiguration<Replacement>
    {
        public void Configure(EntityTypeBuilder<Replacement> entity)
        {
            entity.HasKey(e => new { e.UserId, e.GameId, e.ReplaceId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0, 0 });

            entity.HasIndex(e => new { e.GameId, e.ReplaceId }, "replace_game_idx");

            entity.HasIndex(e => e.ReplaceId, "replacements_replace_id_idx");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .HasColumnName("user_id")
                .HasDefaultValueSql("'000'");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4) unsigned zerofill")
                .HasColumnName("game_id")
                .HasDefaultValueSql("'0000'");

            entity.Property(e => e.ReplaceId)
                .HasColumnType("int(3) unsigned zerofill")
                .HasColumnName("replace_id")
                .HasDefaultValueSql("'000'");

            entity.Property(e => e.Number)
                .HasColumnType("int(11)")
                .HasColumnName("number");

            entity.Property(e => e.Period)
                .IsRequired()
                .HasColumnType("enum('Day','Night')")
                .HasColumnName("period")
                .HasDefaultValueSql("'Day'");

            entity.Property(e => e.RepComment)
                .HasColumnType("text")
                .HasColumnName("rep_comment");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Replacement> entity);
    }
}
