// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class SocialUserConfiguration : IEntityTypeConfiguration<SocialUser>
    {
        public void Configure(EntityTypeBuilder<SocialUser> entity)
        {
            entity.HasKey(e => new { e.SiteId, e.UserId })
                .HasName("PRIMARY")
                .HasAnnotation("MySql:IndexPrefixLength", new[] { 0, 0 });

            entity.ToTable("Social_users");

            entity.Property(e => e.SiteId)
                .HasColumnType("smallint(4) unsigned zerofill")
                .HasColumnName("site_id");

            entity.Property(e => e.UserId)
                .HasColumnType("smallint(4) unsigned zerofill")
                .HasColumnName("user_id");

            entity.Property(e => e.UserInfo)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("user_info");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<SocialUser> entity);
    }
}
