// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class TallyConfiguration : IEntityTypeConfiguration<Tally>
    {
        public void Configure(EntityTypeBuilder<Tally> entity)
        {
            entity.ToTable("Tally");

            entity.HasIndex(e => new { e.GameId, e.Day }, "game_id");

            entity.Property(e => e.Id)
                .HasColumnType("int(11)")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Day)
                .HasColumnType("int(11)")
                .HasColumnName("day");

            entity.Property(e => e.GameId)
                .HasColumnType("int(11)")
                .HasColumnName("game_id");

            entity.Property(e => e.Misc)
                .HasMaxLength(50)
                .HasColumnName("misc");

            entity.Property(e => e.Nightfall).HasColumnName("nightfall");

            entity.Property(e => e.NightfallArticle)
                .HasColumnType("int(11)")
                .HasColumnName("nightfall_article");

            entity.Property(e => e.Unvote).HasColumnName("unvote");

            entity.Property(e => e.UnvoteArticle)
                .HasColumnType("int(11)")
                .HasColumnName("unvote_article");

            entity.Property(e => e.VoteArticle)
                .HasColumnType("int(11)")
                .HasColumnName("vote_article");

            entity.Property(e => e.VoteCount)
                .HasColumnType("int(11)")
                .HasColumnName("vote_count");

            entity.Property(e => e.Votee)
                .HasColumnType("int(11)")
                .HasColumnName("votee");

            entity.Property(e => e.Voter)
                .HasColumnType("int(11)")
                .HasColumnName("voter");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Tally> entity);
    }
}
