// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class TimezoneConfiguration : IEntityTypeConfiguration<Timezone>
    {
        public void Configure(EntityTypeBuilder<Timezone> entity)
        {
            entity.HasKey(e => e.Zone)
                .HasName("PRIMARY");

            entity.HasIndex(e => e.Gmt, "GMT")
                .IsUnique();

            entity.Property(e => e.Zone)
                .HasMaxLength(1)
                .HasColumnName("zone");

            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(75)
                .HasColumnName("description")
                .HasDefaultValueSql("''");

            entity.Property(e => e.Gmt)
                .HasColumnType("int(11)")
                .HasColumnName("GMT");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Timezone> entity);
    }
}
