// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class UpdateCalendarConfiguration : IEntityTypeConfiguration<UpdateCalendar>
    {
        public void Configure(EntityTypeBuilder<UpdateCalendar> entity)
        {
            entity.ToTable("Update_calendar");

            entity.Property(e => e.Id)
                .HasColumnType("int(5) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Action)
                .IsRequired()
                .HasColumnType("enum('add','delete','update')")
                .HasColumnName("action");

            entity.Property(e => e.CalendarId)
                .HasColumnType("text")
                .HasColumnName("calendar_id");

            entity.Property(e => e.GameId)
                .HasColumnType("int(4)")
                .HasColumnName("game_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UpdateCalendar> entity);
    }
}
