// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class UsersNgramConfiguration : IEntityTypeConfiguration<UsersNgram>
    {
        public void Configure(EntityTypeBuilder<UsersNgram> entity)
        {
            entity.ToTable("Users_ngrams");

            entity.HasIndex(e => e.UserId, "user_id");

            entity.Property(e => e.Id)
                .HasColumnType("bigint(20) unsigned")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Gram)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("gram");

            entity.Property(e => e.N)
                .HasColumnType("smallint(5) unsigned")
                .HasColumnName("n");

            entity.Property(e => e.Position)
                .HasColumnType("smallint(5) unsigned")
                .HasColumnName("position");

            entity.Property(e => e.UserId)
                .HasColumnType("bigint(20) unsigned")
                .HasColumnName("user_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UsersNgram> entity);
    }
}
