// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Persistence.Context;
using Persistence;
using System;

#nullable disable

namespace Persistence.Context.Configurations
{
    public partial class WotwConfiguration : IEntityTypeConfiguration<Wotw>
    {
        public void Configure(EntityTypeBuilder<Wotw> entity)
        {
            entity.ToTable("Wotw");

            entity.Property(e => e.Id)
                .HasColumnType("int(3) unsigned zerofill")
                .ValueGeneratedNever()
                .HasColumnName("id");

            entity.Property(e => e.Num)
                .HasColumnType("int(3)")
                .HasColumnName("num");

            entity.Property(e => e.StartDate)
                .HasColumnType("date")
                .HasColumnName("start_date");

            entity.Property(e => e.ThreadId)
                .HasColumnType("int(11)")
                .HasColumnName("thread_id");

            entity.Property(e => e.UserId)
                .HasColumnType("int(3) unsigned zerofill")
                .HasColumnName("user_id");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Wotw> entity);
    }
}
