// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class AmRole
    {
        public uint Id { get; set; }
        public int TemplateId { get; set; }
        public uint RoleId { get; set; }
        public string Side { get; set; } = default!;
        public string GameAction { get; set; } = default!;
        public string? ActionDesc { get; set; }
        public string? GroupName { get; set; }
        public string N0Knows { get; set; } = default!;
        public string N0View { get; set; } = default!;
        public string? ViewResult { get; set; }
        public string RevealAs { get; set; } = default!;
        public string Attribute { get; set; } = default!;
        /// <summary>
        /// 0=false, 1=true
        /// </summary>
        public bool AHidden { get; set; }
        /// <summary>
        /// 0=false,1=true
        /// </summary>
        public bool Parity { get; set; }
        public string Promotion { get; set; } = default!;
        /// <summary>
        /// Yes means keeps current parity status after promotion, does not gain promoted roles parity status.
        /// </summary>
        public string PromotionParity { get; set; } = default!;
        public sbyte RequireRole { get; set; }
    }
}