// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class AmTemplate
    {
        public uint Id { get; set; }
        public ushort OwnerId { get; set; }
        public string Name { get; set; } = default!;
        public string Description { get; set; } = default!;
        public int NumPlayers { get; set; }
        public string NumPlayerSets { get; set; } = default!;
        /// <summary>
        /// If changed edit &quot;expand_role_reveal&quot; in edit_functions.php
        /// </summary>
        public string RoleReveal { get; set; } = default!;
        public string RandomN0 { get; set; } = default!;
        /// <summary>
        /// if changed edit expand_priest_type in edit_functions.php
        /// </summary>
        public string PriestType { get; set; } = default!;
        /// <summary>
        /// 0=false, 1=true
        /// </summary>
        public bool RandomTinker { get; set; }
        /// <summary>
        /// 0=false, 1=true
        /// </summary>
        public bool RandomWhitehat { get; set; }
        public string Mode { get; set; } = default!;
    }
}