// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Bio
    {
        public uint UserId { get; set; }
        /// <summary>
        /// BGG Avatar
        /// </summary>
        public string? Avatar { get; set; }
        /// <summary>
        /// Real Life Name
        /// </summary>
        public string? RlName { get; set; }
        /// <summary>
        /// E-mail Address
        /// </summary>
        public string? EmailAddr { get; set; }
        /// <summary>
        /// Twitter Name
        /// </summary>
        public string? TwitterName { get; set; }
        /// <summary>
        /// Origin of Username
        /// </summary>
        public string? NameOrigin { get; set; }
        /// <summary>
        /// Birthday
        /// </summary>
        public DateTime? BDate { get; set; }
        /// <summary>
        /// Gender
        /// </summary>
        public string? Gender { get; set; }
        /// <summary>
        /// Location
        /// </summary>
        public string? Location { get; set; }
        /// <summary>
        /// Time Zone
        /// </summary>
        public string? TimeZone { get; set; }
        /// <summary>
        /// &lt;a href=&apos;http://en.wikipedia.org/wiki/MBTI&apos;&gt;MBTI&lt;/a&gt;
        /// </summary>
        public string? Mbti { get; set; }
        /// <summary>
        /// Typical Hours to Play WW
        /// </summary>
        public string? FreeHours { get; set; }
        /// <summary>
        /// Job
        /// </summary>
        public string? Job { get; set; }
        /// <summary>
        /// Family
        /// </summary>
        public string? Family { get; set; }
        /// <summary>
        /// Religion
        /// </summary>
        public string? Religion { get; set; }
        /// <summary>
        /// Max New Chat Posts (0=All)
        /// </summary>
        public int MaxMessages { get; set; }
        /// <summary>
        /// Anything Else
        /// </summary>
        public string? Comments { get; set; }
        /// <summary>
        /// Chat Color Preference
        /// </summary>
        public string? ChatColor { get; set; }
    }
}