// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class CcInfo
    {
        public ushort GameId { get; set; }
        public ushort UserId { get; set; }
        public DateTime ClaimTime { get; set; }
        public short? ChallengerId { get; set; }
        public string? TypeError { get; set; }
        public string? DescError { get; set; }
    }
}