// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class ChatMessageAction
    {
        public int Id { get; set; }
        public int MessageId { get; set; }
        public int TypeId { get; set; }
        public int TargetId { get; set; }
        public string Misc { get; set; } = default!;
    }
}