// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class ChatRoom
    {
        public uint Id { get; set; }
        public uint GameId { get; set; }
        public string Name { get; set; } = default!;
        public string Lock { get; set; } = default!;
        public int? MaxPost { get; set; }
        public int? RemainingPost { get; set; }
        public DateTime Created { get; set; }
        public int Monitor { get; set; }
    }
}