// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class ChatUser
    {
        public uint RoomId { get; set; }
        public uint UserId { get; set; }
        public string? Alias { get; set; }
        public string? Secret { get; set; }
        public DateTime LastView { get; set; }
        public string Color { get; set; } = default!;
        public string Lock { get; set; } = default!;
        public int? MaxPost { get; set; }
        public int? RemainingPost { get; set; }
        public DateTime Open { get; set; }
        public DateTime? Close { get; set; }
    }
}