// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Exit
    {
        public uint Id { get; set; }
        public uint GameId { get; set; }
        public string Name { get; set; } = default!;
        public string? TravelText { get; set; }
        public uint? TemplateId { get; set; }
        public string? Comment { get; set; }
        public DateTime Created { get; set; }
    }
}