// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class GameOrder
    {
        public uint Id { get; set; }
        public int UserId { get; set; }
        public int GameId { get; set; }
        public string Desc { get; set; } = default!;
        public int? TargetId { get; set; }
        public string UserText { get; set; } = default!;
        public short? Cancel { get; set; }
        public int Day { get; set; }
        public DateTime LastUpdated { get; set; }
    }
}