// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Game
    {
        public uint Id { get; set; }
        public int? Number { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime? EndDate { get; set; }
        public string Title { get; set; } = default!;
        public string Status { get; set; } = default!;
        public string Winner { get; set; } = default!;
        public int? ThreadId { get; set; }
        public int? ParentGameId { get; set; }
        public string? Description { get; set; }
        /// <summary>
        /// Used to specify that the game starts when full
        /// </summary>
        public string Swf { get; set; } = default!;
        public int? AproxLength { get; set; }
        public int? MaxPlayers { get; set; }
        public int? PlayerListId { get; set; }
        public string Complex { get; set; } = default!;
        public string Phase { get; set; } = default!;
        public int Day { get; set; }
        public string GameOrder { get; set; } = default!;
        public string AutoVt { get; set; } = default!;
        public string AllowNightfall { get; set; } = default!;
        public string AllowNolynch { get; set; } = default!;
        public string VoteByAlias { get; set; } = default!;
        public string PhysByAlias { get; set; } = default!;
        public string AliasDisplay { get; set; } = default!;
        public bool UpdatedTally { get; set; }
        public string DawnChatReset { get; set; } = default!;
        /// <summary>
        /// moderator will be notified if a player hasn&apos;t posted in x amount of hours
        /// </summary>
        public int? MissingHr { get; set; }
        /// <summary>
        /// If Standard then lynch_time and na_deadline should be set, if Fast then day_lenght and night_length should be set
        /// </summary>
        public string DeadlineSpeed { get; set; } = default!;
        public TimeSpan? LynchTime { get; set; }
        public TimeSpan? NaDeadline { get; set; }
        public TimeSpan? DayLength { get; set; }
        public TimeSpan? NightLength { get; set; }
        /// <summary>
        /// if this is set dawn and dusk will be automatically posted by cassy.  This time is the mimimum length that day should last on day1 and if there is a delay posting a deadline.
        /// </summary>
        public TimeSpan? AutoDeadline { get; set; }
        public int? AutomodId { get; set; }
        public string? AutomodState { get; set; }
        public DateTime AutomodPhaseChange { get; set; }
        /// <summary>
        /// used by any game with auto dawn/dusk selected to indicate when the next one should be posted.
        /// </summary>
        public DateTime? AutomodNextdeadline { get; set; }
        public bool? AutomodWeekend { get; set; }
        public DateTime? AutomodRunning { get; set; }
        public DateTime? AutomodTimestamp { get; set; }
        public string? CalendarId { get; set; }
        public string Expired { get; set; } = default!;
        public byte? PhysMoveLimit { get; set; }
        public byte? PhysItemLimit { get; set; }
        public string PhysResetMoves { get; set; } = default!;
        public int? SeriesId { get; set; }
    }
}