// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Item
    {
        public uint Id { get; set; }
        public uint TemplateId { get; set; }
        public uint GameId { get; set; }
        public string Name { get; set; } = default!;
        public uint? OwnerRefId { get; set; }
        public string OwnerType { get; set; } = default!;
        public string? Description { get; set; }
        public string Visibility { get; set; } = default!;
        public string Mobility { get; set; } = default!;
        public int? RoomId { get; set; }
        public string? RoomAlias { get; set; }
        public string? RoomColor { get; set; }
        public DateTime Created { get; set; }
    }
}