// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class LocExit
    {
        public uint LocFromId { get; set; }
        public uint LocToId { get; set; }
        public uint ExitId { get; set; }
    }
}