// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Moderator
    {
        public uint UserId { get; set; }
        public uint GameId { get; set; }
        public string? Comment { get; set; }
    }
}