// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class PhysicsProcessing
    {
        public uint Id { get; set; }
        public uint GameId { get; set; }
        public string Type { get; set; } = default!;
        public string Frequency { get; set; } = default!;
        public byte Minute { get; set; }
        public byte? Hour { get; set; }
        public DateTime? LastRun { get; set; }
    }
}