// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Player
    {
        public uint UserId { get; set; }
        public uint GameId { get; set; }
        public string? RoleName { get; set; }
        public uint RoleId { get; set; }
        public string? Side { get; set; }
        public string GameAction { get; set; } = default!;
        public string? GaDesc { get; set; }
        public string GaText { get; set; } = default!;
        public string? GaGroup { get; set; }
        public short? GaLock { get; set; }
        public string? ModComment { get; set; }
        public string? UserComment { get; set; }
        public DateTime UpdateTime { get; set; }
        public string? DeathPhase { get; set; }
        public short? DeathDay { get; set; }
        public bool? NeedReplace { get; set; }
        public short? AutomodRoleId { get; set; }
        public short? AutomodPromotedId { get; set; }
        public sbyte? NeedToConfirm { get; set; }
        public bool ToughLives { get; set; }
        public string? PlayerAlias { get; set; }
        public string AliasColor { get; set; } = default!;
        public uint? LocId { get; set; }
        public uint? ModchatId { get; set; }
        public ushort? PhysMoveLimit { get; set; }
        public uint? PhysItemLimit { get; set; }
        public ushort PhysMoves { get; set; }
    }
}