// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Replacement
    {
        public uint UserId { get; set; }
        public uint GameId { get; set; }
        public uint ReplaceId { get; set; }
        public string Period { get; set; } = default!;
        public int Number { get; set; }
        public string? RepComment { get; set; }
    }
}