// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Role
    {
        public uint Id { get; set; }
        public string Type { get; set; } = default!;
    }
}