// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class SocialSite
    {
        public ushort Id { get; set; }
        public string SiteName { get; set; } = default!;
        public string? Url { get; set; }
        public string Category { get; set; } = default!;
        public string? Link { get; set; }
    }
}