// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Tally
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int Day { get; set; }
        public int? Votee { get; set; }
        public int Voter { get; set; }
        public int VoteArticle { get; set; }
        public int VoteCount { get; set; }
        public bool Unvote { get; set; }
        public int? UnvoteArticle { get; set; }
        public bool Nightfall { get; set; }
        public int? NightfallArticle { get; set; }
        public string? Misc { get; set; }
    }
}