// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Timezone
    {
        public string Zone { get; set; } = default!;
        public int Gmt { get; set; }
        public string Description { get; set; } = default!;
    }
}