// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class UpdateCalendar
    {
        public uint Id { get; set; }
        public string Action { get; set; } = default!;
        public string? CalendarId { get; set; }
        public int? GameId { get; set; }
    }
}