// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class UsersNgram
    {
        public ulong Id { get; set; }
        public ulong UserId { get; set; }
        public ushort N { get; set; }
        public ushort Position { get; set; }
        public string Gram { get; set; } = default!;
    }
}