// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Vote
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public int ArticleId { get; set; }
        public int Day { get; set; }
        public int Voter { get; set; }
        public int? Votee { get; set; }
        public string Type { get; set; } = default!;
        public string? Misc { get; set; }
        public bool? Valid { get; set; }
        public bool Edited { get; set; }
    }
}