// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class WolfyPlayer
    {
        public uint AwardId { get; set; }
        public uint UserId { get; set; }
        public int Year { get; set; }
        public int AwardPost { get; set; }
    }
}