// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable enable

namespace Domain.Entities
{
    public partial class Wotw
    {
        public uint Id { get; set; }
        public uint UserId { get; set; }
        public int Num { get; set; }
        public DateTime StartDate { get; set; }
        public int ThreadId { get; set; }
    }
}